[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm i -g pnpm@latest && pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm build",
  "cp -r public .next/standalone/public",
  "cp -r .next/static .next/standalone/.next/static"
]

[start]
cmd = "node .next/standalone/server.js"
